server:
  port: 9011

spring:
  application:
    name: tensquare-manager

eureka:
  client:
    service-url: #注册中心地址
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true

zuul:
  routes:
    tensquare_user:
      path: /user/**            #后边加微服务的路径
      serviceId: tensquare-user #服务在eureka注册中心中的id
    tensquare_qa:
      path: /qa/**
      serviceId: tensquare-qa
    tensquare_base:
      path: /base/**
      serviceId: tensquare-base
    tensquare_recruit:
      path: /recruit/**
      serviceId: tensquare-recruit