server:
  port: 9001

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: root
  application:
    name: tensquare_base
#  jpa:
#    database: mysql
#    show-sql: true
mybatis:
  mapper-locations: mapper/*.xml

logging:
  level:
    com.tensquare.base.mapper.*: debug