server:
  port: 9002
spring:
  application:
    name: tensquare-recruit #指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_recruit?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
